version: '3.7'
services:
  win-build:
    image: electronuserland/builder:wine
    volumes:
      # cache
      - ~/.cache/electron:/root/.cache/electron
      - ~/.cache/electron/builder:/root/.cache/electron-builder
      - ../builder-node-modules:/project/node_modules
      - ../:/project
    command: bash -c "yarn && yarn dist -w"
